Repository BHP-DevHub/react-timeline-9000, pull requests merged in 2018-07, with the labels that each got.

#32 Feature/time snapping
  src/demo.js
  src/timeline.js
  src/utils/itemUtils.js
  src/utils/itemUtils.test.js
  src/utils/timeUtils.js
  src/utils/timeUtils.test.js
Labels: feature

#37 Better demo page
  package.json
  src/demo.js
  yarn.lock
Labels: feature

#41 Fix timbar resolution
  src/components/timebar.js
  src/consts/timebarConsts.js
  src/demo.js
Labels: feature

#43 Zoom Functionality
  src/demo.js
Labels: feature

#45 Fix a most sneaky bug
  src/components/timebar.js
  src/timeline.js
Labels: bug

#53 Feature/multi select
  README.md
  src/components/selector.js
  src/demo.js
  src/style.css
  src/timeline.js
Labels: feature

#55 group offset z-index
  README.md
  src/style.css
Labels: bug

#58 RO Timeline
  .tern-project
  src/demo.js
  src/timeline.js
Labels: feature

#60 Feature/selection bug
  src/demo.js
  src/timeline.js
  src/utils/timeUtils.test.js
Labels: bug

#71 updated demo
  README.md
  src/demo.js
  src/demo/customRenderers.js
  src/timeline.js
Labels: bug, feature

#72 Bugfix/various bugs
  src/components/renderers.js
  src/components/timebar.js
  src/demo/customRenderers.js
  src/index.js
  src/timeline.js
  src/utils/itemUtils.js
Labels: bug

#73 Selection box only triggered in grid (not in groups)
  src/timeline.js
Labels: bug

#74 Fix refs issue.
  src/timeline.js
Labels: bug

#75 Fix select box bug
  src/timeline.js
Labels: bug

#76 Grid wasn't adapting to change in width
  src/timeline.js
Labels: bug
